export class Compiler {
    constructor(scene) {
        this.scene = scene;
    }

    compile() {
        const nodes = this.scene.getFlatList();
        
        let htmlBody = "";
        let cssContent = "";

        // Reset CSS
        cssContent += `/* Auto-generated by Vectra */\n`;
        cssContent += `body { margin: 0; padding: 0; overflow: hidden; background-color: #ffffff; }\n`;
        cssContent += `.artboard { position: relative; width: 100vw; height: 100vh; overflow: hidden; }\n\n`;

        nodes.forEach((node) => {
            // Skip root
            if (node.type === 'root') return;

            const id = `node-${node.id.substr(0,4)}`;
            
            // 1. Generate CSS
            cssContent += `.${id} {\n`;
            cssContent += `  position: absolute;\n`;
            cssContent += `  left: ${Math.round(node.props.x)}px;\n`;
            cssContent += `  top: ${Math.round(node.props.y)}px;\n`;
            
            if (node.type === 'rect') {
                cssContent += `  width: ${Math.round(node.props.w)}px;\n`;
                cssContent += `  height: ${Math.round(node.props.h)}px;\n`;
                if (node.props.fill && node.props.fill !== 'none') {
                    cssContent += `  background-color: ${node.props.fill};\n`;
                }
            } 
            else if (node.type === 'text') {
                cssContent += `  font-family: ${node.props.fontFamily}, sans-serif;\n`;
                cssContent += `  font-size: ${node.props.fontSize}px;\n`;
                cssContent += `  color: ${node.props.color};\n`;
                cssContent += `  white-space: pre;\n`;
                cssContent += `  line-height: 1;\n`;
            }
            else if (node.type === 'path') {
                // For paths, dimensions are determined by the SVG bounds
                // We don't set width/height on the div container for paths strictly unless calculated
                // but for absolute positioning we rely on SVG viewBox
            }
            cssContent += `}\n\n`;

            // 2. Generate HTML
            if (node.type === 'rect') {
                htmlBody += `    <div class="${id}"></div>\n`;
            } 
            else if (node.type === 'text') {
                htmlBody += `    <div class="${id}">${node.props.text}</div>\n`;
            } 
            else if (node.type === 'path' && node.props.points.length > 0) {
                const pts = node.props.points;
                const minX = Math.min(...pts.map(p => p.x));
                const minY = Math.min(...pts.map(p => p.y));
                const w = Math.max(...pts.map(p => p.x)) - minX;
                const h = Math.max(...pts.map(p => p.y)) - minY;
                
                // SVG Path Data (Relative to its own box)
                const d = pts.map((p, i) => `${i===0?'M':'L'}${p.x - minX} ${p.y - minY}`).join(' ');
                
                // Override CSS for path wrapper to match bounds
                cssContent += `.${id} { width: ${w}px; height: ${h}px; left: ${Math.round(minX)}px; top: ${Math.round(minY)}px; }\n`;
                
                htmlBody += `    <div class="${id}">\n`;
                htmlBody += `      <svg width="100%" height="100%" style="overflow:visible">\n`;
                htmlBody += `        <path d="${d}" stroke="${node.props.stroke}" stroke-width="${node.props.strokeWidth}" fill="none" />\n`;
                htmlBody += `      </svg>\n`;
                htmlBody += `    </div>\n`;
            }
        });

        // 3. Construct Full HTML File
        const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vectra Export</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="artboard">
${htmlBody}
    </div>
    <script src="script.js"></script>
</body>
</html>`;

        // 4. Construct JS File (Placeholder for now)
        const js = `
document.addEventListener('DOMContentLoaded', () => {
    console.log("🚀 Vectra Design Loaded");
    // Add interaction logic here
});
`;

        return { html, css: cssContent, js };
    }
}